Add Server types
laravel/forge-sdk pull request #102
Opened 2021-02-07 01:39 UTC by tfevens

This PR adds the newly announced `types` to the Server class.

Available types were added to the ServerTypes helper class, as implemented in f3c91f348ea8a8e802cc62b7fe8332f4dc792b6a.

2021-02-07 10:23 UTC, jbrooksuk requested changes

2021-02-07 10:23 UTC, jbrooksuk commented on src/Resources/Server.php
> +     * The name of the server.
This should be:

```suggestion
     * The type of the server.
```

2021-02-07 10:23 UTC, jbrooksuk commented on src/Resources/ServerTypes.php
> +    const DATABASE = 'database';
We're missing the `worker` type here.

2021-02-08 11:56 UTC, tfevens commented
Thanks for catching!  Updated the PR with the requested fixes.

2021-02-15 11:59 UTC, jbrooksuk commented
LGTM!

2021-02-15 12:15 UTC, driesvints commented
@tfevens the PR contains some of the commits from master. Please re-send this with you your own commits and no merge commits. Thanks

2021-02-15 12:15 UTC, closed without merging